### ISSUE TITLE
alarm on sleep ?

### ISSUE THREAD

**Issue by ranshalit** [tbouron/ShakeDetector#4]
Hi,

Thank you for sharing this library.
I see that on suspend it is stopped, and so does no give alarms.
Can't accelerometer give alarms (and wake up from suspend) ?

I see in another device I have (mediatek watch) that it has built-in movement detection, which (*probably*) wakes up from sleep (I see sleep counters increment with "uptime" command), so how did they do it ? 

Thank you for the time,
Ran

**Comment by ranshalit** [comment]
Hi,

I've added link for the "image" of this feature in the watch:
https://drive.google.com/file/d/0B22GsWueReZTVXpPNGVkMU53Vms/view?usp=sharing

Thank you,
Ran

**Comment by tbouron** [comment]
Hi @ranshalit 

The example I gave is in a context of an activity, i.e. sensor data is sent only when the activity is in a foreground. That's why the callback is not called when the phone is put on sleep.

I'm not really sure how to achieve what you want but a wild guess would be to use a `BroadcastReceiver` which would initialize the library as well as acquire a `WAVE_LOCK` (either partial or full) to always get data from the sensor.

Anyway, this is not related to the library in itself but more about how you use it, therefore I'll close the issue. But good luck for your project :)
